# Generated by Django 3.2.2 on 2021-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_tips', '0002_newspost_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
