# Generated by Django 3.2.2 on 2021-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_tips', '0003_auto_20211004_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='photo',
            field=models.ImageField(default=True, upload_to='Newsphotos/%Y/%m/%d/'),
        ),
    ]
