# Generated by Django 3.2.2 on 2021-07-23 08:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.ImageField(upload_to='photos_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo_main', models.ImageField(upload_to='photos_main')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos_sub')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos_sub')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos_sub')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos_sub')),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('website', models.CharField(blank=True, default='#', max_length=150)),
                ('facebook', models.CharField(blank=True, default='#', max_length=150)),
                ('instagram', models.CharField(blank=True, default='#', max_length=150)),
                ('opening_time', models.CharField(blank=True, max_length=7, null=True)),
                ('closing_time', models.CharField(blank=True, max_length=7, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True)),
                ('category', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.category')),
            ],
        ),
    ]
