# Generated by Django 3.2.2 on 2021-07-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
