# Generated by Django 3.2.2 on 2021-08-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='facebook',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='listing',
            name='instagram',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='listing',
            name='website',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
